version: "3.8"

services:
  app:
    build: .
    container_name: adbs_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - redis
    networks:
      - adbs

  nginx:
    image: nginx:alpine
    container_name: adbs-nginx
    restart: unless-stopped
    ports:
      - 8011:80
    depends_on:
      - app
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - adbs

  redis:
    image: redis:alpine
    container_name: adbs-redis
    restart: unless-stopped
    networks:
      - adbs

networks:
  adbs:
